version: 0.2
env:
  variables:
    APP_NAME: "demo_front_cloud"
phases:
  install:
    runtime-versions:
      nodejs: 14.x
    commands:
      - echo INSTALL DEPENDENCES
      - npm install && npm install -g @angular/cli
  build:
    commands:
      - echo BUILD APLICATION
      - ng build --configuration=production
  post_build:
    commands:
      - echo build process finished, we should uplload to S3 now
      - cd dist/$APP_NAME
      - ls -la
